[build-system]
requires = ["setuptools>=45", "wheel", "cmake"]
build-backend = "setuptools.build_meta"

[project]
name = "mpitrampoline4jax"
authors = [
    {name = "Filippo Vicentini"}
]
version = "0.1.0"
description = "MPITrampoline integration for JAX"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "jax>=0.4",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
]